---
Description: "A task to install drpcli task runner as a service on start up"
Name: "drpcli-install"
Templates:
  - ID: "drpcli.etc.tmpl"
    Name: "drpcli.etc"
    Path: "drpcli.etc"
  - ID: "drpcli.etc.export.tmpl"
    Name: "drpcli.etc.export"
    Path: "drpcli.etc.export"
  - ID: "drpcli.service.tmpl"
    Name: "drpcli.service"
    Path: "drpcli.service"
  - ID: "drpcli-init.service.tmpl"
    Name: "drpcli-init.service"
    Path: "drpcli-init.service"
  - ID: "drpcli.sysv.tmpl"
    Name: "drpcli.sysv"
    Path: "drpcli.sysv"
  - ID: "drpcli-init.sysv.tmpl"
    Name: "drpcli-init.sysv"
    Path: "drpcli-init.sysv"
  - ID: "drpcli.unit.tmpl"
    Name: "drpcli.unit"
    Path: "drpcli.unit"
  - ID: "drpcli-init.unit.tmpl"
    Name: "drpcli-init.unit"
    Path: "drpcli-init.unit"
  - ID: "drpcli-install.sh.tmpl"
    Name: "Install DRP Cli and setup a service to run it on startup."
    Path: ""
Meta:
  icon: "motorcycle"
  color: "blue"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
