Description: An array of ansible playbook repos to run
Documentation: |
  Ansible Playbooks Local
  -----------------------

  The objects define ansible playbooks to get and execute.

  The properties of each item in the array:

  * name: name of ansible playbook (required) - will be used as a directory name
  * path: subdirectory inside repo (required)
  * playbook: playbook filename (required)
  * repo: url of git repo (required)
  * commit: a specific commit or branch to checkout
  * args: additional command line arguments
  * verbosity: verbosity level - should be `--verbose` if set

  example:

    ::

      [
        {
          "name": "helloworld",
          "path": "",
          "playbook": "helloworld.yml",
          "repo": "https://github.com/ansible/tower-example"
        }
      ]
Meta:
  color: black
  icon: git
  title: RackN Content
Name: ansible/playbooks
Schema:
  default: []
  type: array
  items:
    type: object
    required:
      - name
      - repo
      - path
      - playbook
    properties:
      name:
        type: string
      path:
        type: string
      repo:
        type: string
      playbook:
        type: string
      args:
        type: string
      verbosity:
        type: string
      commit:
        type: string
Secure: false

