---
Description: "A task to install consul"
Name: "consul-install"
Documentation: |
  Installs (but not configures) consul, to be used as an HA backend to Vault
OptionalParams:
  - consul/server-count
  - consul/version
Templates:
  - ID: "consul-install.sh.tmpl"
    Name: "Configure consul"
    Path: ""    
Meta:
  icon: "book"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
