---
Description: "DEV: Reset Profile values between Test Runs"
Name: "krib-dev-reset"
Documentation: |
  Clears Created Params: krib/*, etcd/*
RequiredParams:
  - krib/cluster-profile
  - etcd/cluster-profile
OptionalParams:
  - krib/cluster-is-production
Templates:
- Contents: |-
    #!/bin/bash
    # Reset CA params
    set -e
    # we need a random backoff for races
    SLEEP=$[ ( $RANDOM % 5 ) ]
    sleep $SLEEP
    declare -a WIPE_PARAMS=('etcd/client-ca-name' 'etcd/client-ca-pw' 'etcd/peer-ca-name' 'etcd/peer-ca-pw' 'etcd/server-ca-name' 'etcd/server-ca-pw')
    {{if .ParamExists "etcd/cluster-profile" -}}
    CLUSTER_PROFILE={{.Param "etcd/cluster-profile"}}
    PROFILE_TOKEN={{.GenerateProfileToken (.Param "etcd/cluster-profile") 7200}}
    {{else -}}
    echo "Missing etcd/cluster-profile on the machine!"
    exit 1
    {{end -}}
    {{template "setup.tmpl" .}}
    {{template "krib-dev-reset.sh.tmpl" .}}
    echo "YOU MUST RESET THE CA BY HAND!"
    echo "==========================================================================="
    echo "drpcli plugins runaction certs deleteroot certs/root etcd-cluster-client-ca"
    echo "drpcli plugins runaction certs deleteroot certs/root etcd-cluster-server-ca"
    echo "drpcli plugins runaction certs deleteroot certs/root etcd-cluster-peer-ca"
    echo "==========================================================================="
    echo "done CA params reset"
  Name: CA clear
- Contents: |-
    #!/bin/bash
    # Reset etcd params
    set -e
    declare -a WIPE_PARAMS=('etcd/servers' 'etcd/servers-done')
    declare CLUSTER_TYPE="etcd"
    {{template "setup.tmpl" .}}
    {{if .ParamExists "etcd/cluster-profile" -}}
    CLUSTER_PROFILE={{.Param "etcd/cluster-profile"}}
    PROFILE_TOKEN={{.GenerateProfileToken (.Param "etcd/cluster-profile") 7200}}
    {{else -}}
    echo "Missing etcd/cluster-profile on the machine!"
    exit 1
    {{end -}}
    {{template "krib-dev-reset.sh.tmpl" .}}
    echo "done etcd params reset"
  Name: etcd-reset  
- Contents: |-
    #!/bin/bash
    # Reset KRIB params
    set -e
    declare -a WIPE_PARAMS=('krib/cluster-masters' 'krib/cluster-master-vip' 'krib/cluster-join-command' 'krib/cluster-admin-conf' 'krib/cluster-master-certs')
    {{template "setup.tmpl" .}}
    {{if .ParamExists "krib/cluster-profile" -}}
    CLUSTER_PROFILE={{.Param "krib/cluster-profile"}}
    PROFILE_TOKEN={{.GenerateProfileToken (.Param "krib/cluster-profile") 7200}}
    {{else -}}
    echo "Missing krib/cluster-profile on the machine!"
    exit 1
    {{end -}}
    {{template "krib-dev-reset.sh.tmpl" .}}
    echo "done KRIB params reset"
  Name: KRIB clear
Meta:
  icon: "ship"
  color: "red"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
