---
Description: "A task to configure kubernetes via kubeadm"
Name: "krib-config"
Documentation: |
  Configure Kubernetes using Kubeadm
  This uses the Digital Rebar Cluster pattern so krib/cluster-profile must be set
RequiredParams:
  - krib/cluster-profile
OptionalParams:
  - krib/cluster-name
  - krib/cluster-is-production
Templates:
  - ID: "krib-kubeadm.cfg.tmpl"
    Name: "Kubeadm config file"
    Path: "/tmp/kubeadm.cfg"
  - ID: "krib-config.sh.tmpl"
    Name: "Config Kubernetes via Kubeadm"
    Path: ""
Meta:
  icon: "ship"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
