---
Description: "A task to force time setting for now"
Name: "krib-set-time"
Templates:
  - Contents: |
      #!/bin/bash
      {{ template "setup.tmpl" }}
      set -e
      test ! $(which ntpdate > /dev/null 2>&1) && install ntpdate
      ntpdate -s time.apple.com
    Name: "Set Time"
Meta:
  icon: "ship"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
