---
Description: "A task to install Helm and Tiller and any defined Charts"
Name: "krib-helm"
Documentation: |
  Installs Helm and runs helm init (which installs Tiller) on the leader.
  Installs Charts defined in helm/charts.
  This uses the Digital Rebar Cluster pattern so krib/cluster-profile must be set.

  The install checks to see if tiller is running and may skip initialization.
RequiredParams:
  - krib/cluster-profile
OptionalParams:
  - helm/charts
  - helm/version
Templates:
  - ID: "krib-helm.cfg.tmpl"
    Name: "Service Account for Tiller"
    Path: "tiller-rbac.yaml"
  - ID: "krib-helm-init.sh.tmpl"
    Name: "Bringing up Helm and Tiller on Master"
    Path: ""
  - ID: "krib-helm.sh.tmpl"
    Name: "Running Helm Charts"
    Path: ""
Meta:
  icon: "ship"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
