---
Description: "A task to install kubernetes and kubeadm"
Name: "kubernetes-install"
Documentation: |
  Downloads Kubernetes installation components from repos
  This task relies on the O/S packages being updated
  and accessible.
  NOTE: Access to update repos is required!
RequredParams:
  - krib/cluster-profile
OptionalParams:
  - krib/cluster-name
  - krib/cluster-is-production
  - krib/cluster-join
  - krib/cluster-master-certs
  - krib/cluster-master-count
  - krib/cluster-master-vip
  - krib/cluster-master-on-etcds
  - krib/cluster-masters
  - krib/operate-action
  - krib/operate-on-node
  - krib/operate-options
Templates:
  - ID: "kubernetes-install.sh.tmpl"
    Name: "Install Kubernetes and Kubeadm"
    Path: ""
Meta:
  icon: "ship"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
