Description: Wipe Disks for RancherOS
Documentation: |
  Wipe Disks for RancherOS
Errors: []
Meta:
  color: black
  feature-flags: sane-exit-codes
  icon: unlinkify
  title: RackN Content
Name: rancheros-wipe-disks
Templates:
- Contents: |-
    #!/bin/bash
    # Wipe rancheros to the disk

    set -e

    echo "Force wipe and format /dev/sda"
    mkfs.ext4 -F -L RANCHER_STATE /dev/sda
    echo "Finished successfully"
    exit 0
  Name: rancheros-wipe-disks
