---
Name: "krib-config"
Description: "KRIB configure a Kubernetes cluster master and/or worker nodes"
RunnerWait: true
Tasks:
  - "krib-get-masters"
  - "krib-config"
Meta:
  icon: "ship"
  color: "yellow"
  title: "Community Content"
