---
Name: "erase-hard-disks-for-os-install"
Description: |
  Erases any data on the hard disks that might confuse the OS install
  process.  This includes LVM metadata, partition tables, software RAID signatures,
  and the first and last megabyte of any partitions and disks.
Meta:
  feature-flags: "sane-exit-codes"
  icon: "erase"
  color: "blue"
  title: "Digital Rebar Community Content"
Templates:
  - Name: "erase-disks"
    Contents: |
      #!/bin/bash
      # Nuke it all.
      declare vg pv maj min blocks name
      # Make sure that the kernel knows about all the partitions
      for bd in /sys/block/sd*; do
          [[ -b /dev/${bd##*/} ]] || continue
          partprobe "/dev/${bd##*/}" || :
      done
      # Zap any volume groups that may be lying around.
      vgscan --ignorelockingfailure -P
      while read vg; do
          vgremove -ff -y "$vg" || :
      done < <(vgs --noheadings -o vg_name)
      # Wipe out any LVM metadata that the kernel may have detected.
      pvscan --ignorelockingfailure
      while read pv; do
          pvremove -ff -y "$pv" || :
      done < <(pvs --noheadings -o pv_name)
      # Now zap any partitions along with any RAID metadata that may exist.
      while read maj min blocks name; do
          [[ -b /dev/$name && -w /dev/$name && $name != name ]] || continue
          [[ $name = loop* ]] && continue
          [[ $name = dm* ]] && continue
          [[ $name = fd* ]] && continue
          mdadm --misc --zero-superblock --force /dev/$name || :
          if (( blocks >= 2048)); then
              dd "if=/dev/zero" "of=/dev/$name" "bs=512" "count=2048"
              dd "if=/dev/zero" "of=/dev/$name" "bs=512" "count=2048" "seek=$(($blocks - 2048))"
          else
              dd "if=/dev/zero" "of=/dev/$name" "bs=512" "count=$blocks"
          fi
      done < <(tac /proc/partitions)
