---
Name: "gohai"
Description: "Get basic system inventory using Gohai"
Templates:
  - Name: "gohai"
    Contents: |
      #!/usr/bin/env bash
      drpcli machines set {{.Machine.UUID}} set gohai-inventory to "$(gohai)"
Meta:
  icon: "search"
  color: "blue"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
