---
Name: "gohai"
Description: "Get basic system inventory using Gohai"
Templates:
  - Name: "gohai"
    Contents: |
      #!/usr/bin/env bash
      gohai | drpcli machines set {{.Machine.UUID}} param gohai-inventory to -
Meta:
  icon: "search"
  color: "blue"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
